[2024-07-07T05:12:57.181+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-07T05:12:43.382151+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-07T05:12:57.183+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-07T05:12:43.382151+00:00 permission to 509
[2024-07-07T05:12:57.184+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-07T05:12:57.185+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-07T05:12:57.226+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-07T05:12:43.382151+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-07T05:12:57.227+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-07T05:12:43.382151+00:00 permission to 509
[2024-07-07T05:12:57.229+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-07T05:12:57.230+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-07T05:12:57.258+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-07T05:12:43.382151+00:00 [queued]>
[2024-07-07T05:12:57.264+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-07T05:12:43.382151+00:00 [queued]>
[2024-07-07T05:12:57.265+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-07T05:12:57.281+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): AutoML_PyCaret> on 2024-07-07 05:12:43.382151+00:00
[2024-07-07T05:12:57.293+0000] {standard_task_runner.py:60} INFO - Started process 1687 to run task
[2024-07-07T05:12:57.299+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'AutoML_workflow_demo', 'AutoML_PyCaret', 'manual__2024-07-07T05:12:43.382151+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dmc_pipeline.py', '--cfg-path', '/tmp/tmpne9vqwvs']
[2024-07-07T05:12:57.300+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask AutoML_PyCaret
[2024-07-07T05:12:57.354+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-07T05:12:43.382151+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-07T05:12:57.355+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-07T05:12:43.382151+00:00 permission to 509
[2024-07-07T05:12:57.356+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-07T05:12:57.357+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-07T05:12:57.358+0000] {task_command.py:423} INFO - Running <TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-07T05:12:43.382151+00:00 [running]> on host 549d24f0d639
[2024-07-07T05:12:57.452+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AutoML_workflow_demo' AIRFLOW_CTX_TASK_ID='AutoML_PyCaret' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T05:12:43.382151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T05:12:43.382151+00:00'
[2024-07-07T05:13:00.543+0000] {logging_mixin.py:188} INFO -                     Description                                 Value
0                    Session id                                   123
1                        Target                                Target
2                   Target type                            Multiclass
3                Target mapping  Dropout: 0, Enrolled: 1, Graduate: 2
4           Original data shape                           (76518, 37)
5        Transformed data shape                           (76518, 37)
6   Transformed train set shape                           (53562, 37)
7    Transformed test set shape                           (22956, 37)
8              Numeric features                                    36
9                    Preprocess                                  True
10              Imputation type                                simple
11           Numeric imputation                                  mean
12       Categorical imputation                                  mode
13               Fold Generator                       StratifiedKFold
14                  Fold Number                                    10
15                     CPU Jobs                                    -1
16                      Use GPU                                 False
17               Log Experiment                                 False
18              Experiment Name                      clf-default-name
19                          USI                                  7ff9
[2024-07-07T05:13:00.788+0000] {logging_mixin.py:188} WARNING - Processing:   0%|          | 0/61 [00:00<?, ?it/s]
[2024-07-07T05:13:00.889+0000] {logging_mixin.py:188} WARNING - Processing:   7%|6         | 4/61 [00:00<00:01, 39.68it/s]
[2024-07-07T05:13:20.783+0000] {logging_mixin.py:188} WARNING - Processing:   7%|6         | 4/61 [00:19<00:01, 39.68it/s]
[2024-07-07T05:18:46.684+0000] {logging_mixin.py:188} WARNING - Processing:   8%|8         | 5/61 [05:45<1:24:56, 91.02s/it]
[2024-07-07T05:18:47.532+0000] {logging_mixin.py:188} WARNING - Processing:  11%|#1        | 7/61 [05:46<46:55, 52.14s/it]  
[2024-07-07T05:19:01.033+0000] {logging_mixin.py:188} WARNING - Processing:  13%|#3        | 8/61 [06:00<46:03, 52.14s/it]
[2024-07-07T05:19:54.883+0000] {logging_mixin.py:188} WARNING - Processing:  15%|#4        | 9/61 [06:54<39:06, 45.12s/it]
[2024-07-07T05:19:55.272+0000] {logging_mixin.py:188} WARNING - Processing:  18%|#8        | 11/61 [06:54<24:25, 29.31s/it]
[2024-07-07T05:19:58.049+0000] {logging_mixin.py:188} WARNING - Processing:  21%|##1       | 13/61 [06:57<15:58, 19.97s/it]
[2024-07-07T05:19:58.446+0000] {logging_mixin.py:188} WARNING - Processing:  25%|##4       | 15/61 [06:57<10:24, 13.58s/it]
[2024-07-07T05:20:07.288+0000] {logging_mixin.py:188} WARNING - Processing:  28%|##7       | 17/61 [07:06<07:50, 10.68s/it]
[2024-07-07T05:20:07.650+0000] {logging_mixin.py:188} WARNING - Processing:  31%|###1      | 19/61 [07:06<05:11,  7.42s/it]
[2024-07-07T05:21:07.996+0000] {logging_mixin.py:188} WARNING - Processing:  34%|###4      | 21/61 [08:07<09:36, 14.42s/it]
[2024-07-07T05:21:08.359+0000] {logging_mixin.py:188} WARNING - Processing:  38%|###7      | 23/61 [08:07<06:22, 10.07s/it]
[2024-07-07T05:21:11.075+0000] {logging_mixin.py:188} WARNING - Processing:  41%|####      | 25/61 [08:10<04:27,  7.43s/it]
[2024-07-07T05:21:11.556+0000] {logging_mixin.py:188} WARNING - Processing:  44%|####4     | 27/61 [08:10<02:58,  5.25s/it]
[2024-07-07T05:21:32.612+0000] {logging_mixin.py:188} WARNING - Processing:  48%|####7     | 29/61 [08:31<03:38,  6.84s/it]
[2024-07-07T05:21:33.129+0000] {logging_mixin.py:188} WARNING - Processing:  51%|#####     | 31/61 [08:32<02:25,  4.86s/it]
[2024-07-07T05:21:40.494+0000] {logging_mixin.py:188} WARNING - Processing:  54%|#####4    | 33/61 [08:39<02:06,  4.51s/it]
[2024-07-07T05:21:40.919+0000] {logging_mixin.py:188} WARNING - Processing:  57%|#####7    | 35/61 [08:40<01:23,  3.22s/it]
[2024-07-07T05:22:05.572+0000] {logging_mixin.py:188} WARNING - Processing:  61%|######    | 37/61 [09:04<02:22,  5.95s/it]
[2024-07-07T05:22:05.877+0000] {logging_mixin.py:188} WARNING - Processing:  64%|######3   | 39/61 [09:05<01:32,  4.21s/it]
[2024-07-07T05:26:12.220+0000] {logging_mixin.py:188} WARNING - Processing:  67%|######7   | 41/61 [13:11<13:18, 39.92s/it]
[2024-07-07T05:26:12.574+0000] {logging_mixin.py:188} WARNING - Processing:  70%|#######   | 43/61 [13:11<08:23, 27.99s/it]
[2024-07-07T05:26:18.813+0000] {logging_mixin.py:188} WARNING - Processing:  74%|#######3  | 45/61 [13:18<05:28, 20.53s/it]
[2024-07-07T05:26:19.169+0000] {logging_mixin.py:188} WARNING - Processing:  77%|#######7  | 47/61 [13:18<03:21, 14.42s/it]
[2024-07-07T05:26:41.379+0000] {job.py:213} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 308, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-07T05:26:41.451+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-07-07T05:26:56.603+0000] {logging_mixin.py:188} WARNING - Processing:  80%|########  | 49/61 [13:55<03:08, 15.71s/it]
[2024-07-07T05:26:57.150+0000] {logging_mixin.py:188} WARNING - Processing:  84%|########3 | 51/61 [13:56<01:50, 11.08s/it]
[2024-07-07T05:32:29.136+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
