[2024-07-06T04:14:59.751+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T04:09:36.417584+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-06T04:14:59.752+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T04:09:36.417584+00:00 permission to 509
[2024-07-06T04:14:59.753+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-06T04:14:59.753+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-06T04:14:59.777+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T04:09:36.417584+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-06T04:14:59.778+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T04:09:36.417584+00:00 permission to 509
[2024-07-06T04:14:59.779+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-06T04:14:59.780+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-06T04:14:59.804+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-06T04:09:36.417584+00:00 [queued]>
[2024-07-06T04:14:59.808+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-06T04:09:36.417584+00:00 [queued]>
[2024-07-06T04:14:59.809+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-06T04:14:59.817+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): AutoML_PyCaret> on 2024-07-06 04:09:36.417584+00:00
[2024-07-06T04:14:59.825+0000] {standard_task_runner.py:60} INFO - Started process 590 to run task
[2024-07-06T04:14:59.828+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'AutoML_workflow_demo', 'AutoML_PyCaret', 'manual__2024-07-06T04:09:36.417584+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dmc_pipeline.py', '--cfg-path', '/tmp/tmpl6f9wiq9']
[2024-07-06T04:14:59.829+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask AutoML_PyCaret
[2024-07-06T04:14:59.859+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T04:09:36.417584+00:00/task_id=AutoML_PyCaret permission to 509
[2024-07-06T04:14:59.860+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo/run_id=manual__2024-07-06T04:09:36.417584+00:00 permission to 509
[2024-07-06T04:14:59.861+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=AutoML_workflow_demo permission to 509
[2024-07-06T04:14:59.861+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs permission to 509
[2024-07-06T04:14:59.862+0000] {task_command.py:423} INFO - Running <TaskInstance: AutoML_workflow_demo.AutoML_PyCaret manual__2024-07-06T04:09:36.417584+00:00 [running]> on host 2ed3ddbbb77c
[2024-07-06T04:14:59.913+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AutoML_workflow_demo' AIRFLOW_CTX_TASK_ID='AutoML_PyCaret' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T04:09:36.417584+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-06T04:09:36.417584+00:00'
[2024-07-06T04:15:00.151+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dmc_pipeline.py", line 63, in AutoML_PyCaret
    exp_pc01 = setup(data= df_train,
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/classification/functional.py", line 595, in setup
    return exp.setup(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/classification/oop.py", line 715, in setup
    self._initialize_setup(
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 328, in _initialize_setup
    self._check_environment()
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/internal/pycaret_experiment/pycaret_experiment.py", line 121, in _check_environment
    self.logger.info(show_versions(logger=self.logger))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/utils/_show_versions.py", line 165, in show_versions
    optional_deps_info = _get_deps_info(logger=logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/utils/_show_versions.py", line 130, in _get_deps_info
    ver = get_module_version(modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/utils/_dependencies.py", line 81, in get_module_version
    version = _get_module_version(modname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/utils/_dependencies.py", line 75, in _get_module_version
    installed_modules[modname] = _try_import_and_get_module_version(modname)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pycaret/utils/_dependencies.py", line 28, in _try_import_and_get_module_version
    mod = import_module(modname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.11/site-packages/lightgbm/__init__.py", line 9, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/home/airflow/.local/lib/python3.11/site-packages/lightgbm/basic.py", line 279, in <module>
    _LIB = _load_lib()
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/lightgbm/basic.py", line 263, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libgomp.so.1: cannot open shared object file: No such file or directory
[2024-07-06T04:15:00.166+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=AutoML_workflow_demo, task_id=AutoML_PyCaret, execution_date=20240706T040936, start_date=20240706T041459, end_date=20240706T041500
[2024-07-06T04:15:00.175+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task AutoML_PyCaret (libgomp.so.1: cannot open shared object file: No such file or directory; 590)
[2024-07-06T04:15:00.201+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-06T04:15:00.217+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
